const mongoose = require("mongoose");

/**
 * ChatMessage — a single turn inside a ChatSession.
 *
 * Every user message AND every assistant reply is stored here.
 * The `structuredData` field holds the rich payload (product cards,
 * comparison tables, budget plans) that the frontend renders directly —
 * keeping the plain `content` field as a human-readable fallback.
 *
 * role values mirror the OpenAI message format so the conversation
 * history can be forwarded to the API without transformation.
 */
const chatMessageSchema = mongoose.Schema(
  {
    sessionId: {
      type: String,
      required: true,
      index: true,
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: "User",
      index: true,
    },

    // "user"      → message typed by the shopper
    // "assistant" → response generated by the AI pipeline
    // "system"    → internal context injections (never shown in UI)
    role: {
      type: String,
      enum: ["user", "assistant", "system"],
      required: true,
    },

    // The raw natural-language text of the message.
    content: {
      type: String,
      required: true,
      trim: true,
    },

    // Tells the frontend WHICH renderer to use for this message.
    //   "text"         → plain ChatMessage bubble
    //   "product_list" → grid of ProductCard components
    //   "comparison"   → ComparisonTable component
    //   "budget_plan"  → BudgetPlanResult component
    //   "clarification"→ question bubble + follow-up chips
    contentType: {
      type: String,
      enum: ["text", "product_list", "comparison", "budget_plan", "clarification"],
      default: "text",
    },

    // Only populated on assistant messages.
    structuredData: {
      // Product ObjectIds that were shown to the user in this turn.
      // Cross-referenced with the product collection on the client side.
      products: [
        {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Product",
        },
      ],

      // Per-product reasons explaining WHY it was recommended.
      // Parallel array to `products` — index 0 reasons match product 0.
      reasons: [
        {
          productId: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
          points: [String], // e.g. ["Fits ₹40,000 budget", "Highest rated"]
        },
      ],

      // The full comparison payload rendered by ComparisonTable.jsx
      comparisonTable: {
        type: mongoose.Schema.Types.Mixed,
        default: null,
      },

      // The full budget plan rendered by BudgetPlanResult.jsx
      budgetPlan: {
        type: mongoose.Schema.Types.Mixed,
        default: null,
      },

      // Quick-reply chips shown below the assistant message.
      // Clicking one fires the chip text as the next user message.
      followUpSuggestions: [String],
    },

    // OpenAI token counts for this single turn (0 for user messages).
    tokensUsed: {
      type: Number,
      default: 0,
    },

    // End-to-end latency for the AI pipeline (ms). Useful for p95 monitoring.
    responseTimeMs: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

const ChatMessage = mongoose.model("ChatMessage", chatMessageSchema);

module.exports = ChatMessage;
